# Generated by Django 5.2.8 on 2025-12-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_reclamation_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='priority',
        ),
    ]
