# Generated by Django 5.2.8 on 2025-12-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_remove_reclamation_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='sentiment_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
