# Generated by Django 5.2.8 on 2025-12-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0004_reclamation_sentiment_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['-date']},
        ),
    ]
