# Generated by Django 5.2.8 on 2025-12-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0005_alter_reclamation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
    ]
