# Generated by Django 5.2.8 on 2026-01-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0006_reclamation_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='', max_length=20),
        ),
    ]
