# Generated by Django 5.2.8 on 2026-01-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0007_alter_reclamation_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
